INSERT ALL
  INTO STG3_SIRE_ADM.NS_POSITION_OF_TRUST_LIST
  (APPLICATION_KEY, ORGANIZATION_ID, PARTICIPANT_ID, PARTICIPANT_NAME, NOTIFICATION_BASIS_CODE,
   TITLE, POSITION_OF_TRUST, ENTITY_OF_POSITION_OF_TRUST, END_DATE)
  VALUES ('POSTR',10012785,10012821,'BROWN JAMES','POSOTR_001',NULL,'Trusted man','Trusting company 1',TO_DATE('31-DEC-1999','DD-MON-YYYY'))
  INTO STG3_SIRE_ADM.NS_POSITION_OF_TRUST_LIST
  VALUES ('POSTR',10012785,10012822,'ÅKE TEST–JUNIOR–FIRST','POSOTR_002',NULL,'Trusted junior','Trusting company 2',TO_DATE('31-DEC-1999','DD-MON-YYYY'))
  -- ...add the rest...
SELECT 1 FROM dual;

COMMIT;
-------------------------------------------
